default: &default
  adapter: postgresql
  encoding: unicode
  username: gschool
  pool: 5

development:
  <<: *default
  database: g3-assessment-week-12-development-2

test:
  <<: *default
  database: g3-assessment-week-12-test-2
